In [ ]:
import pandas as pd

df = pd.read_csv(r"D:\CapCut\customer_shopping_behavior.csv")

In [19]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [25]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [28]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [28]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [31]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(
    lambda x: x.fillna(x.median())
)

In [36]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [51]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'}, inplace=True)

print(df.columns)

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [67]:
labels = ['Young Adult', 'Adult', 'Middle-Aged', 'Senior']

df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)
print(df[['age', 'age_group']].head())

   age    age_group
0   55  Middle-Aged
1   19  Young Adult
2   50  Middle-Aged
3   21  Young Adult
4   45  Middle-Aged

In [75]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Annually': 365,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Every 3 Months': 90,
    'Monthly': 30
}

df['frequency_Days'] = df['frequency_of_purchases'].map(frequency_mapping)

print(df[['frequency_of_purchases', 'frequency_Days']].head(10))

  frequency_of_purchases  frequency_Days
0            Fortnightly              14
1            Fortnightly              14
2                 Weekly               7
3                 Weekly               7
4               Annually             365
5                 Weekly               7
6              Quarterly              90
7                 Weekly               7
8               Annually             365
9              Quarterly              90

In [81]:
print(df[['discount_applied','promo_code_used']].head(10))

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [86]:
df = df.drop('promo_code_used', axis=1)

In [88]:
print(df[['discount_applied']].head(10))

  discount_applied
0              Yes
1              Yes
2              Yes
3              Yes
4              Yes
5              Yes
6              Yes
7              Yes
8              Yes
9              Yes

In [91]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-cp314-cp314-win_amd64.whl (18.2 MB)
   ---------------------------------------- 0.0/18.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/18.2 MB ? eta -:--:--
    --------------------------------------- 0.3/18.2 MB ? eta -:--:--
   - -------------------------------------- 0.5/18.2 MB 1.5 MB/s eta 0:00:12
   - -------------------------------------- 0.8/18.2 MB 1.7 MB/s eta 0:00:11
   -- ------------------------------------- 1.3/18.2 MB 1.7 MB/s eta 0:00:10
   ---- ----------------------------------- 1.8/18.2 MB 1.8 MB/s eta 0:00:09
   ----- ---------------------------------- 2.4/18.2 MB 2.0 MB/s eta 0:00:09
   ------ --------------------------------- 2.9/18.2 MB 2.1 MB/s eta 0:00:08
   ------- -------------------------------- 3.4/18.2 MB 2.2 MB/s eta 0:00:07
   --------- ------------------------------ 4.2/18.2 MB 2.3 MB/s eta 0:00:07
   ---------- ----------------------------- 4.7/18.2 MB 2.4 MB/s eta 0:00:06
   ------------ --------------------------- 5.5/18.2 MB 2.5 MB/s eta 0:00:06
   ------------- -------------------------- 6.3/18.2 MB 2.7 MB/s eta 0:00:05
   --------------- ------------------------ 7.1/18.2 MB 2.7 MB/s eta 0:00:05
   ----------------- ---------------------- 8.1/18.2 MB 2.9 MB/s eta 0:00:04
   -------------------- ------------------- 9.2/18.2 MB 3.1 MB/s eta 0:00:03
   ---------------------- ----------------- 10.2/18.2 MB 3.2 MB/s eta 0:00:03
   ------------------------ --------------- 11.3/18.2 MB 3.3 MB/s eta 0:00:03
   --------------------------- ------------ 12.3/18.2 MB 3.4 MB/s eta 0:00:02
   ----------------------------- ---------- 13.6/18.2 MB 3.5 MB/s eta 0:00:02
   -------------------------------- ------- 14.7/18.2 MB 3.6 MB/s eta 0:00:01
   ----------------------------------- ---- 16.0/18.2 MB 3.7 MB/s eta 0:00:01
   ------------------------------------ --- 16.8/18.2 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  18.1/18.2 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 18.2/18.2 MB 3.7 MB/s  0:00:05
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: C:\Users\jsart\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [92]:
import mysql.connector

conn = mysql.connector.connect(
    host="127.0.0.1",
    port=3306,
    user="root",
    password="Sarthak@2004"
)

print("Connected Successfully")

Connected Successfully

In [93]:
import mysql.connector

conn = mysql.connector.connect(
    host="127.0.0.1",
    port=3306,
    user="root",
    password="Sarthak@2004",
    database="project_db"
)

print("Connected Successfully")

Connected Successfully

In [96]:
cursor = conn.cursor()

cursor.execute("SHOW TABLES")
print(cursor.fetchall())

[]

In [97]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.51)
Requirement already satisfied: pymysql in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: C:\Users\jsart\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [98]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("Sarthak@2004")

engine = create_engine(
    f"mysql+pymysql://root:{password}@127.0.0.1:3306/project_db"
)

df.to_sql(
    'customer',   # table name in MySQL
    con=engine,
    if_exists='replace',
    index=False
)

print("Data uploaded successfully")

Data uploaded successfully